### PR TITLE
Rewrite system check with py2

### PR DESCRIPTION
**Pull request by k-okada**
Should I clean up commit log?

### CODE REVIEW

**Comment by 130s** [comment]
> Should I clean up commit log?

I can rebase once it's merged; I feel like giving a try to have verbose commits in PReq and once megerd squash them so that we can keep track of individual commits at PReq page and still keep the upstream commit history simple.

Build failed for Groovy only, both DEB and not.

https://travis-ci.org/start-jsk/rtmros_hironx/jobs/28595887

```
make[2]: Leaving directory `/home/travis/ros/ws_rtmros_hironx/build/rtm-ros-robotics/openrtm_common/hrpsys/build/hrpsys-base'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/travis/ros/ws_rtmros_hironx/build/rtm-ros-robotics/openrtm_common/hrpsys/build/hrpsys-base'
#
touch installed
grep: /home/travis/ros/ws_rtmros_hironx/build/rtm-ros-robotics/openrtm_common/hrpsys/build/hrpsys-base/install_manifest.txt: No such file or directory
CMake Error at rtm-ros-robotics/openrtm_common/hrpsys/catkin.cmake:49 (message):
grep :
/home/travis/ros/ws_rtmros_hironx/build/rtm-ros-robotics/openrtm_common/hrpsys/build/hrpsys-base/install_manifest.txt
0
Call Stack (most recent call first):
rtm-ros-robotics/openrtm_common/hrpsys/CMakeLists.txt:2 (include)
-- Configuring incomplete, errors occurred!
Invoking "cmake" failed
```

Does `hrpsys-base/install_manifest.txt` exist?

**Comment by k-okada** [comment]
> Does `hrpsys-base/install_manifest.txt exist?`

that should exists

**Comment by k-okada** [comment]
the problem is

```
[0m[ 79%] Building CXX object rtc/VirtualCamera/CMakeFiles/VirtualCameraComp.dir/GLscene.o
[0m[ 79%] Building CXX object rtc/VirtualCamera/CMakeFiles/VirtualCamera.dir/GLscene.o
[0mg++: internal compiler error: Killed (program cc1plus)
[0mPlease submit a full bug report,
[0mwith preprocessed source if appropriate.
[0mSee <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
[0mmake[3]: *** [rtc/VirtualCamera/CMakeFiles/VirtualCameraComp.dir/VirtualCamera.o] Error 4
[0mmake[3]: *** Waiting for unfinished jobs....
[0mg++: internal compiler error: Killed (program cc1plus)
[0mPlease submit a full bug report,
[0mwith preprocessed source if appropriate.
[0mSee <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
[0mmake[3]: *** [rtc/VirtualCamera/CMakeFiles/VirtualCamera.dir/Virt
```

this happens only when travis does not allocate enough memory to each job and that usually happens `high time` in US (later afternoon?)

**Comment by 130s** [comment]
> this happens only when travis does not allocate enough memory to each job and that usually happens high time in US (later afternoon?)

Whoa, I see. [Added](http://wiki.ros.org/rtmros_common#A.28travis.29_g.2B-.2B-:_internal_compiler_error:_Killed_.28program_cc1plus.29) to common error case.
And re-run `travis` passed except for the variants failing due to [the same cause as others](https://github.com/start-jsk/rtmros_hironx/pull/118#issuecomment-47415193). So, merging.

**Comment by 130s** [comment]
> >    Should I clean up commit log?
> 
> I can rebase once it's merged; I feel like giving a try to have verbose commits in PReq and once megerd squash them so that we can keep track of individual commits at PReq page and still keep the upstream commit history simple.

Turned out this strategy doesn't easily work, especially after merging multiple PReqs each of which is distinct, since squashing between X and Y commits is impossible with simple `git` command AFAIK (squashing works for commits `AFTER` the commit X). 

So this I just leave as it is. From next time we might need to clean the commit log if necessary.

**Pull request merged**
