### PR TITLE
Add Indigo to travis test config.

### PR DESCRIPTION
**Pull request by 130s**

### CODE REVIEW

**Comment by k-okada** [comment]
this is not a easy job, just adding ROS_DISTRO=indigo will not work

First, travis does not support 14.04 yet, it only provide 12.04, it is 
scheduled, but not happened so far (
https://github.com/travis-ci/travis-ci/issues/2046)

travis provide docker support, but it not able to sudo inside docker, so 
you can not install ros libraries, or you have to build docker image for 
each job  (
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
)

we're using jsk_travis package 
https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis_jenkins.py 
which send job to other machine and running job within custom docker image, 
this is working, but it is not stable, our jenkins machine stops very 
often, Also jsk_travis system is so messy that it's very hard to 
understand, but if you feel you can understand this, I'll recommend to use 
that package.

## 

◉ Kei Okada

**Comment by 130s** [comment]
That sounds not easy at all. I'll then keep this PR open and wait for things to become ready.

**Comment by k-okada** [comment]
~~seems it is working https://github.com/tork-a/rtmros_nextage/pull/149~~

sorry for confusion, I said travis PR seems working, but someone need to configure for indigo, so this PR is not solved yet

**Comment by 130s** [comment]
@k-okada Please review, this PR is updated.

**Comment by 130s** [comment]
Re-triggering travis.

**Comment by 130s** [comment]
Looks like travis is still failing because `ros-indigo-catkin` is [at this moment not built yet in the shadow-fixed](http://www.ros.org/debbuild/indigo.html?q=catkin). We'll have to wait and re-trigger again.

**Comment by 130s** [comment]
This should be targeted against `indigo-devel`. Closing in favor of #400

**Pull request closed without merging**
