### PR TITLE
(hironx_client.py) fix #107

### LINKED ISSUE #107: hironx init pose may not be set factory initial value
I don't know if this applies to all Hiro but for some newer robots, the pose `HIRONX.goInitial` sets is different from its factory initial pose.

For `NextageClient`, [it's adjusted](https://github.com/tork-a/rtmros_nextage/commit/1391e19961c80784e5ad510dcee1dd50aa708934#diff-74831e17eddab0218a7f6d7fbc024a30).

Unless there's a need I want the same value for `HIRONX` so that I can use the same code between Hiro and NXO.

I can't find a commit log where the current value was set ([log](https://code.google.com/p/rtm-ros-robotics/source/list?path=/trunk/rtmros_hironx/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py&start=6889)).

### PR DESCRIPTION
**Pull request by 130s**

### CODE REVIEW

**Comment by k-okada** [comment]
seems good, we have trouble on travis(see below, I'm still not sure what has changed), restarted old build that passed a few days ago
https://travis-ci.org/start-jsk/rtmros_hironx/builds/26487519

https://github.com/start-jsk/rtmros_gazebo/pull/71
https://github.com/start-jsk/hrpsys/issues/90

**Comment by 130s** [comment]
> we have trouble on travis(see below, I'm still not sure what has changed), restarted old build that passed a few days ago

Now https://travis-ci.org/start-jsk/rtmros_hironx/builds/26487519 failed.

The build for the PReq in question (#110) failed too https://travis-ci.org/start-jsk/rtmros_hironx/builds/27730988.

Mostly `rosbuild` passed while `deb` failed. I'm looking into the logs.

**Comment by 130s** [comment]
Hard for me to debug this; no easy clue found, but only `DEB`s are failing should be a sign. Can we just wait until `hrpsys` 315.2.2 DEB becomes ready on shadow-fixed (the error outputs don't mention that the cause is in the build status of `hrpsys`. It's just one possibility).

Below I just excepted 2 common errors in some travis builds:

```
2/2 Test: _ctest_hironx_ros_bridge_rostest_test_test-hironx-ros-bridge.test
Command: "/home/travis/ros/ws_rtmros_hironx/build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/hydro/share/catkin/cmake/test/run_tests.py" "/home/travis/ros/ws_rtmros_hironx/build/test_results/hironx_ros_bridge/rostest-test_test-hironx-ros-bridge.xml" "--return-code" "/opt/ros/hydro/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge --package=hironx_ros_bridge --results-filename test_test-hironx-ros-bridge.xml /home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/test/test-hironx-ros-bridge.test "
Directory: /home/travis/ros/ws_rtmros_hironx/build/rtmros_hironx/hironx_ros_bridge
"_ctest_hironx_ros_bridge_rostest_test_test-hironx-ros-bridge.test" start time: Jun 17 11:58 UTC
Output:
----------------------------------------------------------
ready
loading /home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/models/kawada-hironx.dae
:
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
The model was successfully loaded !
Warning: Model HiroNX has empty joint ID in the valid IDs.
cache found for /home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/models/kawada-hironx.dae
Warning: Model HiroNX has empty joint ID in the valid IDs.
cache found for /home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/models/kawada-hironx.dae
[ WARN] [1403006333.621034714]: [HrpsysSeqStateROSBridge] use_hrpsys_time
[ INFO] [1403006333.656535014]: [HrpsysSeqStateROSBridge] @Initilize name : HrpsysSeqStateROSBridge0
Warning: Model HiroNX has empty joint ID in the valid IDs.
cache found for /home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/models/kawada-hironx.dae
Warning: Model HiroNX has empty joint ID in the valid IDs.
[rtmlaunch] starting... /opt/ros/hydro/share/hrpsys_ros_bridge/launch/hrpsys_ros_bridge.launch
[rtmlaunch] RTCTREE_NAMESERVERS localhost:2809 localhost:2809
[rtmlaunch] SIMULATOR_NAME HiroNX(Robot)0
[rtmlaunch] check connection/activation
[rtmlaunch] Wait for /localhost:2809/HiroNX(Robot)0.rtc:q 0 /30
[rtmlaunch] starting... /opt/ros/hydro/share/hrpsys_ros_bridge/launch/collision_detector.launch
[rtmlaunch] RTCTREE_NAMESERVERS is not set, use localhost:15005
[rtmlaunch] RTCTREE_NAMESERVERS localhost:15005 localhost:15005
[rtmlaunch] SIMULATOR_NAME HiroNX(Robot)0
[rtmlaunch] check connection/activation
[rtmlaunch] [ERROR] Could not Connect ( /localhost:15005/HiroNX(Robot)0.rtc:q , /localhost:15005/CollisionDetector0.rtc:qCurrent ): Invalid CORBA naming service: localhost:15005
[rtmlaunch] Could not Activate ( localhost:15005/CollisionDetector0.rtc ) : Invalid CORBA naming service: localhost:15005
[rtmlaunch] Catch signal 'SIGINT', exitting...
[rtmlaunch] Catch signal 'SIGINT', exitting...
state_publisher: /usr/include/boost/thread/pthread/pthread_mutex_scoped_lock.hpp:26: boost::pthread::pthread_mutex_scoped_lock::pthread_mutex_scoped_lock(pthread_mutex_t*): Assertion `!pthread_mutex_lock(m)' failed.
Traceback (most recent call last):
File "/home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/scripts/hironx.py", line 10, in <module>
from hironx_ros_bridge import hironx_client
File "/home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py", line 44, in <module>
from hrpsys.hrpsys_config import *
File "/opt/ros/hydro/lib/python2.7/dist-packages/hrpsys/hrpsys_config.py", line 7, in <module>
[ INFO] [1403006333.543937907]: [HrpsysJointTrajectoryBridge] @Initilize name : HrpsysJointTrajectoryBridge0 done
* unrecognized tag rtconnect
* unrecognized tag rtactivate
... logging to /home/travis/.ros/log/rostest-testing-worker-linux-8-1-12530-linux-9-27730993-27942.log
[ROSUNIT] Outputting test results to /home/travis/ros/ws_rtmros_hironx/build/test_results/hironx_ros_bridge/rostest-test_test-hironx-ros-bridge.xml
testtest_hironx_ros_bridge ... FAILURE!
FAILURE: Test Fixture Nodes ['hrpsys', 'CollisionDetectorComp'] failed to launch
File "/usr/lib/python2.7/unittest/case.py", line 327, in run
testMethod()
File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/runner.py", line 122, in fn
self.assert_(not failed, "Test Fixture Nodes %s failed to launch"%failed)
File "/usr/lib/python2.7/unittest/case.py", line 420, in assertTrue
raise self.failureException(msg)
--------------------------------------------------------------------------------
[ROSTEST]-----------------------------------------------------------------------
[testtest_hironx_ros_bridge][failed]
SUMMARY
* RESULT: FAIL
* TESTS: 0
* ERRORS: 0
* FAILURES: 1
ERROR: The following tests failed to run:
```

**Comment by k-okada** [comment]
something wrong on test_hironx.py

```
[ROSTEST]-----------------------------------------------------------------------

[hironx_ros_bridge.rosunit-test_hironx/testSetTargetPoseBothArm][ERROR]---------
getCurrentPosition() takes exactly 2 arguments (3 given)
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/test/test_hironx.py", line 550, in testSetTargetPoseBothArm
    posl1 = self.robot.getCurrentPosition('LARM_JOINT5')
  File "/home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py", line 640, in getCurrentPosition
    self._EEF_JOINT_NAMES)
```

**Comment by 130s** [comment]
That error message looks like taken from other pull request; for example I don't see the string `_EEF_JOINT_NAMES`, in https://travis-ci.org/start-jsk/rtmros_hironx/jobs/27730991

**Comment by k-okada** [comment]
on groovy, we have to wait few more hours for hrpsys 315.2.2 https://github.com/ros/rosdistro/pull/4771#issuecomment-46329582

```
Get:57 http://packages.ros.org/ros-shadow-fixed/ubuntu/ precise/main ros-groovy-hrpsys amd64 315.2.1-2precise-20140614-0758-+0000 [4,999 kB]
```

**Comment by 130s** [comment]
Now looks like with hrpsys 315.2.2 travis passes with Hydro. For Groovy it builds fine, but is not yet available from shadow-fixed.

**Comment by k-okada** [comment]
synced in shadow-fixed,http://packages.ros.org/ros-shadow-fixed/ubuntu/pool/main/r/ros-groovy-hrpsys/, restart again, this should pass the travis

**Pull request merged**
