### PR TITLE
save result to db

### PR DESCRIPTION
**Pull request by k-okada**
save check results to db

### CODE REVIEW

**Comment by 130s** [comment]
@k-okada it's so great if you could combine #199 with this PReq so that I'd be able to test both changes on QNX.

**Comment by 130s** [comment]
But I can do so by myself locally.

**Comment by k-okada** [comment]
ok, merged

**Comment by k-okada** [comment]
?? did i include something wrong??

**Comment by 130s** [comment]
We're holding the review of this due to https://github.com/tork-a/delivery/issues/60#issuecomment-51577433

**Pull request merged**
