### PR TITLE
Manual fix to issue#287 for Hironx.

### PR DESCRIPTION
**Pull request by 130s**
Applying the change suggested in https://github.com/start-jsk/rtmros_hironx/issues/287#issuecomment-64893372 for left and right arms. 
As far as checked visually (making unittest for this issue is in progress at https://github.com/tork-a/rtmros_nextage/pull/133), it looked ok.

### CODE REVIEW

**Comment by k-okada** [comment]
created test code for #287 and why you create new unittest under nextage?

**Comment by k-okada** [comment]
What is the plan ? since robot_model is likely to update to new version on next sync,  are you going to merge this and create new version now, and remove this and create new version after next sync? and release reverted version on next-next sync?

**Comment by 130s** [comment]
https://github.com/start-jsk/rtmros_hironx/issues/287#issuecomment-65016700 tells all. We don't need this patch.

> why you create new unittest under nextage?

Because the model file is different b/w `hironx` and `nextage`, I thought we need tests for both. But even for that purpose, I'm not sure if we need to have 2 different test cases, because all we need is the "run" of the tests against 2 different robots; testcase can be the same. So IMO as long as the test is run against both robots, we should utilize the same test cases.

**Comment by k-okada** [comment]
Ok, I understand, I just curious that it seems you create test code for nxo only not hiro.

**Comment by uesnaola** [comment]
Using the source code of github for nextage_ros_bridge we see that this issue is solved for simulation with nextage, but when we try with the real robot the problem remains. We calculated tfs using the nextage functions getCurrentPosition and getCurrentRPY to compare. I attach a picture  
screenshot from 2015-03-05 10_42_30

We tfs names `LARM_JOINTx_Link` are originals and the ones named `LARM_JOINTx_Link_Controller` are the ones we generated using nextage functions. You can see that the ones we generated match with the 3D model but the others not so I can not figure out where should the parsing error happen.

Another hint is that works for simulation but not for the real robot. Apart of the wrl model stored in the QNX of the robot, is there any other difference between simulation and real robot?

**Comment by emijah** [comment]
Hello everyone,

Is the deviation always in the Z direction?

If so, it could be because the `LARM_JOINTX_Link_Controller` points are
calculated using the command angles to the joints, and `LARM_JOINTX_Link`
points are calculated using the actual angles the robot is at. The
deviation in the Z direction would be the effects of gravity, as neither
Hiro nor Nextage Open has gravity compensation. That said, the amount of
deviation looks pretty large, but then, I don't know what is attached to
the end of the wrist.

Best regards,

Hajime

2015-03-05 21:24 GMT+09:00 uesnaola notifications@github.com:

**Comment by 130s** [comment]
@uesnaola Is it possible for you to share the code you use to publish your custom tf frames (`LARM_JOINTx_Link_Controller`)? 

@emijah Once we have the code is it possible for you to try reproducing the issue on the real robot?

Lacking both the code and the real robot, it's a bit hard for me to replicate the issue.

---

And in response to @emijah, 

> The deviation in the Z direction would be the effects of gravity,

Assuming this is true, then,

> it could be because the `LARM_JOINTX_Link_Controller` points are calculated using the command angles to the joints, and `LARM_JOINTX_Link` points are calculated using the actual angles the robot is at. 

I think this is the opposite. 
- `LARM_JOINTX_Link_Controller` is based on the result values of hrpsys' `getCurrentX` functions, which should be considering the poses from the real robot. Gravity might matter here.
- `LARM_JOINTX_Link` is based rather on models in collada file. So no gravity applied.

If the above is true then `LARM_JOINTX_Link_Controller` shouldn't be located lower than the other.

Ref. https://github.com/start-jsk/rtmros_hironx/issues/213#issuecomment-85037261

After all, I can't yet explain why @uesnaola is seeing this issue.

**Comment by 130s** [comment]
CORRECTION: 

x: If the above is true then `LARM_JOINTX_Link_Controller` shouldn't be located lower than the other.
o: If the above is true then `LARM_JOINTX_Link` shouldn't be located lower than the other.

`LARM_JOINTX_Link` are the ones that are NOT affected by gravity.

**Comment by emijah** [comment]
@130s @uesnaola Okay. I'm afraid I'm rather busy until the 15th. I should be able to replicate the problem after that.

**Pull request closed without merging**
