### PR TITLE
Change the value of the default arguments to WAIST

### PR DESCRIPTION
**Pull request by DaikiMaekawa**
https://github.com/start-jsk/rtmros_hironx/issues/212 Change the default arguments of frame_name to WAIST.

### CODE REVIEW

**Comment by DaikiMaekawa** [comment]
I has already completed the confirmation in simulation and unit test.

**Comment by k-okada** [comment]
traivs said something wrong on https://github.com/start-jsk/rtmros_hironx/blob/hydro-devel/hironx_ros_bridge/test/test_hironx.py#L563 and https://github.com/start-jsk/rtmros_hironx/blob/hydro-devel/hironx_ros_bridge/test/test_hironx.py#L581

```
[ROSTEST]-----------------------------------------------------------------------

[hironx_ros_bridge.rosunit-test_hironx/testGetCurrentPose][ERROR]---------------
Could not find reference : LARM_JOINT5:WAIST:WAIST
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/home/travis/ros/ws_rtmros_hironx/install/share/hironx_ros_bridge/test/test_hironx.py", line 654, in testGetCurrentPose
    raise RuntimeError(e.message)
--------------------------------------------------------------------------------

[hironx_ros_bridge.rosunit-test_hironx/testGetReferencePose][ERROR]-------------
Could not find reference : LARM_JOINT5:WAIST:WAIST
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/home/travis/ros/ws_rtmros_hironx/install/share/hironx_ros_bridge/test/test_hironx.py", line 599, in testGetReferencePose
    raise RuntimeError(e.message)
--------------------------------------------------------------------------------
```

**Comment by DaikiMaekawa** [comment]
@k-okada  Umm... I corrected the error that were pointed out, but travis keeps failing. https://github.com/DaikiMaekawa/rtmros_hironx/commit/1827e91a12441a8926666a57a082f658fa79c6c7

**Comment by k-okada** [comment]
https://travis-ci.org/start-jsk/rtmros_hironx/builds/44556417 tells you that it passed if you use deb version of openhrp3 and hrpsys, but it fails if you use everything from source file.

And https://s3.amazonaws.com/archive.travis-ci.org/jobs/44556423/log.txt tells hrpsys-simulator segfaults, and it is likely that travis is failing to start simulator for some reason.
In this case, we typically restart travis several times and see if it passed.

```
sh: 1: rtcprof: not found
sh: 1: rtcprof: not found
sh: 1: rtcprof: not found
*** glibc detected *** /home/travis/ros/ws_rtmros_hironx/install/lib/hrpsys/hrpsys-simulator: invalid fastbin entry (free): 0x0000000001baef90 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7e626)[0x7fe9ea8ce626]
/opt/ros/hydro/lib/libRTC-1.1.0.so(_ZN9__gnu_cxx13new_allocatorIPN3RTC13ModuleManager9DLLEntityEE10deallocateEPS4_m+0x20)[0x7fe9ebaea23a]
/opt/ros/hydro/lib/libRTC-1.1.0.so(_ZNSt12_Vector_baseIPN3RTC13ModuleManager9DLLEntityESaIS3_EE13_M_deallocateEPS3_m+0x32)[0x7fe9ebae98d0]
/opt/ros/hydro/lib/libRTC-1.1.0.so(_ZNSt6vectorIPN3RTC13ModuleManager9DLLEntityESaIS3_EE13_M_insert_auxEN9__gnu_cxx17__normal_iteratorIPS3_S5_EERKS3_+0x225)
```

**Comment by k-okada** [comment]
and we restarted the travis

**Comment by DaikiMaekawa** [comment]
Because travis passed building on Hydro, may I merge this branch into master?

**Comment by k-okada** [comment]
@snozawa is right, his PR is not good. it does not work on old hrpsys so it will break most of hironx users.
See #304 to avoid problem, but we need more discussion. because we added #298 and break code and add #304 again to fix that. we should remove both of then and fix the problem. may be put code in hrpsys_config.py.

the rules is:
- try to put your code on upstream,
- try to improve function by deleting (shrinking) codes.

**Pull request merged**
