### PR TITLE
travis config to indigo-devel branch

### PR DESCRIPTION
**Pull request by 130s**

### CODE REVIEW

**Comment by 130s** [comment]
https://travis-ci.org/start-jsk/rtmros_hironx/jobs/87581981#L382-L383

```
$ if [ $USE_DEB == false ]; then $ROSWS update   ; fi

ERROR in config: scm type without declared uri in {'local-name': 'rtm-ros-robotics/rtmros_hironx'}
```

But URL is declared https://github.com/130s/rtmros_hironx/blob/add/travis_indigo/.rosinstall#L4-L6

```
- git:
    uri: https://github.com/start-jsk/rtmros_hironx
    local-name: rtm-ros-robotics/rtmros_hironx
```

Don't know what `wstool` complains about. Let's see if #401 resolves this.

**Comment by k-okada** [comment]
If you think you can't fix this soon, please assign me. I think it is not good to merge PR even if Travis returns failure, not only it is not a good custom, but also Travis in hrpsys-base deepens on this package and most of the time hironx is brocker for the test. If hironx maintainer think passing Travis is not important, the there are no reason to force hrpsys developer to check hironx compatibility.

**Comment by 130s** [comment]
> If hironx maintainer think passing Travis is not important

Oh no no :no_good: ! The opposite. CI is getting more and more critical for HiroNXO too. In fact I've been tackling this travis issue on and off for the last few days. I'm sorry if I gave a bad impression and that I have to ask for the help but please fix this then.

##By the way, does travis tests on hrpsys repository directly use travis config on this repository? I thought they have their own travis.yml that runs test cases in hironx packages.

**Comment by k-okada** [comment]
ok, finished, but updating travis to indigo was not a easy job and i think 
it was clever to keep main target to hydro as pr2 still does...

travis tests on hrpsys is not depends on config on this repo, but depends 
on code in this repo, all of changes on hrpsys need to check pass test code 
in hironx. 

## 

◉ Kei Okada

On Thu, Oct 29, 2015 at 10:21 AM, Isaac I.Y. Saito <notifications@github.com

**Comment by 130s** [comment]
Thank you for all the work!

> it was clever to keep main target to hydro as pr2 still does...

Do we want/need to set back to using hydro branch for indigo?

**Comment by k-okada** [comment]
> Do we want/need to set back to using hydro branch for indigo?

## nonono, i just want to say that if it is working, then we'd better to leave it.

◉ Kei Okada

**Pull request merged**
