### PR TITLE
add rosbuild groovy on travis

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by 130s** [comment]
Doesn't this PReq mix patches for `rosbuild` and `catkin`?

**Comment by k-okada** [comment]
It seems so, I forget about this. I restated rosbuild/deb which is the only one setup that didn't pass the test.

**Comment by k-okada** [comment]
the result of build test seems horrible, only catkin/deb passed. 
hrpsys_ros_bridge should have test case that covers all downstream packages, which means if the downstream packages files, that's the problem of the downstream package and we wont have to fix hrpsys_ros_bridge or other packages, if we need to do that, that means we need more test code in hrpsys_ros_bridge.

Thus, first we have to check if there are something misisng in upstream test case, https://github.com/start-jsk/rtmros_common/tree/master/hrpsys_ros_bridge/test, or we have something wrong in this package.
I'll look at this.

**Comment by 130s** [comment]
> the result of build test seems horrible, only catkin/deb passed. 

Which test are you referring to?

If that is [this](http://jenkins.ros.org/job/prerelease-hydro-rtmros_hironx/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=prerelease/1/consoleFull) that we just received, that is pre-release using source, which means this PReq (#63) isn't yet included. Just a little clarification from me.

**Comment by k-okada** [comment]
I'm looking at -> https://travis-ci.org/start-jsk/rtmros_hironx/jobs/21147668

**Comment by k-okada** [comment]
'non-deb' test fails with grep hoge/fuga at https://github.com/start-jsk/rtmros_hironx/pull/63/files#diff-354f30a63fb0907d4ad57269548329e3R59, and groovy/deb fails with lack of pr2_controllers_msgs:

```
Warning: Model HiroNX has empty joint ID in the valid IDs.
[33m[rtmlaunch] Wait for  /localhost:2809/HrpsysSeqStateROSBridge0.rtc:rsangle   0 /30[0m
Traceback (most recent call last):
  File "/home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/test/test_hironx_ros_bridge.py", line 20, in <module>
    roslib.load_manifest('pr2_controllers_msgs')
```

we should release 1.0.8 with depends to ros-groovy-pr2-controllrs-msgs

**Comment by 130s** [comment]
I'm not sure what's the problem here, and I might be missing a point, but first of all why do we need to support `rosbuild` in `rtmros_hironx`? AFAIK all the users of this package are fine with `catkin` (or they use `.deb`).

**Comment by k-okada** [comment]
supporting only catkin is fine for this package.
checking on rosbuild is just for the "service" those who uses rosbuild, for example https://github.com/jsk-ros-pkg/jsk_common/issues/350

**Comment by 130s** [comment]
```
supporting only catkin is fine for this package.
checking on rosbuild is just for the "service" those who uses rosbuild, for example jsk-ros-pkg/jsk_common#350
```

I see, sounds like that is the point of whole this PReq. Although adding `<build_depend>rosbuild</build_depend>` makes me a bit uneasy, I assume that is necessary for `rosmake`ing.

So, I'm almost merging this but `BUILDER=rosbuild USE_DEB=true` failed in [the last travis run](https://travis-ci.org/start-jsk/rtmros_hironx/builds/22424633). Just restarted the job.

**Comment by k-okada** [comment]
>  Although adding <build_depend>rosbuild</build_depend> makes me a bit uneasy, I assume that is necessary for rosmakeing.

That's true , thanks for catching.

Memo: Currently our travis script (not applied to this repository yet), uses package.xml to rosdep install. So it is surprising for me to know rosdep on manifest works on this repository. 

https://github.com/start-jsk/rtmros_common/blob/master/.travis.yml#L53

**Comment by 130s** [comment]
[travis failed](https://travis-ci.org/start-jsk/rtmros_hironx/builds/22424633) again. This time due to the missing `hrpsys_ros_bridge` in `Groovy` (https://github.com/start-jsk/rtmros_common/issues/410) so the cause is external. I merge this now.

**Pull request merged**
