### PR TITLE
add test code to check #287 problem

### PR DESCRIPTION
**Pull request by k-okada**
I'm afraid this will pass the travis since newer version of robot_model is already released in shadow-fixed.
@130s please check if #290 is valid with this PR

### CODE REVIEW

**Comment by 130s** [comment]
> I'm afraid this will pass the travis since newer version of robot_model is already released in shadow-fixed.

I think that's a good thing.
In the future if something changes anywhere in the upstream, this test tells us about that.

Since #290 is closed, I guess we'll be able to merge this once travis passes.

**Comment by 130s** [comment]
hmm travis keeps failing

**Comment by k-okada** [comment]
Get:105 http://packages.ros.org/ros-shadow-fixed/ubuntu/ precise/main
ros-hydro-collada-parser amd64 1.10.21-0precise-20141130-2028-+0000 [172 kB]

it seems travis installed old collda-parser at 6 days ago, restarted travis
again.

## 

◉ Kei Okada

On Fri, Dec 12, 2014 at 12:33 AM, Isaac I.Y. Saito <notifications@github.com

**Comment by 130s** [comment]
I tried a few times to look into the logs but I have no idea why the `test- hironx_ros_bridge.test` fails. @k-okada would you take a look?
By any chance is the cause the same with https://github.com/start-jsk/rtmros_hironx/issues/302?

```
:
[34m#### Running command: [1m"make test -j8 -l8"[0m[34m in [1m"/home/travis/ros/ws_rtmros_hironx/build/rtmros_hironx/hironx_ros_bridge"[0m
[34m####[0m
[36mRunning tests...
[0mTest project /home/travis/ros/ws_rtmros_hironx/build/rtmros_hironx/hironx_ros_bridge
    Start 1: _ctest_hironx_ros_bridge_rostest_test_test-hironx.test
1/2 Test #1: _ctest_hironx_ros_bridge_rostest_test_test-hironx.test ..............   Passed  263.64 sec
    Start 2: _ctest_hironx_ros_bridge_rostest_test_test-hironx-ros-bridge.test
2/2 Test #2: _ctest_hironx_ros_bridge_rostest_test_test-hironx-ros-bridge.test ...***Failed   16.66 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) = 280.30 sec

The following tests FAILED:
      2 - _ctest_hironx_ros_bridge_rostest_test_test-hironx-ros-bridge.test (Failed)
Errors while running CTest
make: *** [test] Error 8
[31mInvoking [1m"make"[22m failed[0m
travis_time:end:24a42bdb:start=1419629382426875332,finish=1419629663012144923,duration=280585269591
[0K
[32;1mThe command "if [ $BUILDER == catkin ]; then catkin_make test --pkg $TARGET_PKG -j8 -l8  ; export EXIT_STATUS=$?; fi" exited with 0.[0m
:
2/2 Testing: _ctest_hironx_ros_bridge_rostest_test_test-hironx-ros-bridge.test
2/2 Test: _ctest_hironx_ros_bridge_rostest_test_test-hironx-ros-bridge.test
Command: "/home/travis/ros/ws_rtmros_hironx/build/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/hydro/share/catkin/cmake/test/run_tests.py" "/home/travis/ros/ws_rtmros_hironx/build/test_results/hironx_ros_bridge/rostest-test_test-hironx-ros-bridge.xml" "--return-code" "/opt/ros/hydro/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge --package=hironx_ros_bridge --results-filename test_test-hironx-ros-bridge.xml /home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/test/test-hironx-ros-bridge.test "
Directory: /home/travis/ros/ws_rtmros_hironx/build/rtmros_hironx/hironx_ros_bridge
"_ctest_hironx_ros_bridge_rostest_test_test-hironx-ros-bridge.test" start time: Dec 26 21:34 UTC
Output:
----------------------------------------------------------
omniORB: Failed to bind to address :: port 2809. Address in use?
omniORB: Error: Unable to create an endpoint of this description: giop:tcp::2809
Failed to initialise the ORB / POA: INITIALIZE_TransportError
Is omniNames already running?
ready
loading file:///home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/models/kawada-hironx.dae
Collada Warning: fill asset info
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
loading /home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/models/kawada-hironx.dae
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
The model was successfully loaded ! 
Warning: Model HiroNX has empty joint ID in the valid IDs.
loading file:///opt/ros/hydro/share/openhrp3/share/OpenHRP-3.1/idl/../../..//share/OpenHRP-3.1/sample/model/longfloor.wrl
Humanoid node
Joint nodeWAIST
  Segment node BODY
The model was successfully loaded ! 
Collada Warning: fill asset info
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
:
[ERROR] [WallTime: 1419629650.906171] [0.000000] [collision_state.py] catch exception, restart rtc_init.
Make sure collision_pair is set in .conf file. See https://github.com/start-jsk/rtmros_common/issues/247
Original exception: CORBA.OBJECT_NOT_EXIST(omniORB.OBJECT_NOT_EXIST_NoMatch, CORBA.COMPLETED_NO)
[rtmlaunch] Connected from localhost:2809/HiroNX(Robot)0.rtc:q
[rtmlaunch]             to localhost:2809/CollisionDetector0.rtc:qRef
[rtmlaunch]           with {'id': '', 'properties': {'dataport.subscription_type': 'flush'}, 'name': None, 'verbose': False}
[rtmlaunch] Activate <- Inactive /localhost:2809/CollisionDetector0.rtc
cache found for file:///home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/models/kawada-hironx.dae
[ERROR] Connection Failed with the Nameserver (hostname=testing-worker-linux-5-2-1931-linux-4-42590583 port=15005).
Make sure the hostname is correct and the Nameserver is running.
CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)
Warning: Model HiroNX has empty joint ID in the valid IDs.
prop[collision_pair] ->RARM_JOINT2:LARM_JOINT2 RARM_JOINT3:LARM_JOINT3 RARM_JOINT4:LARM_JOINT4 RARM_JOINT5:LARM_JOINT5
check collisions between RARM_JOINT2 and LARM_JOINT2
:
[rtm.py]    Connect sh.basePosOut - log.sh_basePosOut
[hrpsys.py]    setupLogger : record type = TimedOrientation3D , name =  baseRpyOut  to  sh_baseRpyOut
[rtm.py]    Connect sh.baseRpyOut - log.sh_baseRpyOut
    def __init__(self, t, v):
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/scripts/hironx.py", line 74, in <module>
    robot.init(robotname=args.robot, url=args.modelfile)
  File "/home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py", line 122, in init
    HrpsysConfigurator.init(self, robotname=robotname, url=url)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/hrpsys/hrpsys_config.py", line 1676, in init
    self.setupLogger()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/hrpsys/hrpsys_config.py", line 645, in setupLogger
    self.connectLoggerPort(self.sh, 'zmpOut')
  File "/opt/ros/hydro/lib/python2.7/dist-packages/hrpsys/hrpsys_config.py", line 613, in connectLoggerPort
    if rtm.findPort(self.log.ref, log_name) == None:
  File "/opt/ros/hydro/lib/python2.7/dist-packages/hrpsys/rtm.py", line 398, in findPort
    cprof = rtc.get_component_profile()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/OpenRTM_aist/RTM_IDL/RTC_idl.py", line 1344, in get_component_profile
    return _omnipy.invoke(self, "get_component_profile", _0_RTC.RTObject._d_get_component_profile, args)
omniORB.CORBA.UNKNOWN: CORBA.UNKNOWN(omniORB.UNKNOWN_PythonException, CORBA.COMPLETED_MAYBE)
terminate called after throwing an instance of 'CORBA::OBJECT_NOT_EXIST'
[0m[ INFO] [1419629649.101662531]: [HrpsysJointTrajectoryBridge] @Initilize name : HrpsysJointTrajectoryBridge0 done[0m
state_publisher: /usr/include/boost/thread/pthread/pthread_mutex_scoped_lock.hpp:26: boost::pthread::pthread_mutex_scoped_lock::pthread_mutex_scoped_lock(pthread_mutex_t*): Assertion `!pthread_mutex_lock(m)' failed.
[0m[ INFO] [1419629649.120904118]: [HrpsysSeqStateROSBridge] Loaded HiroNX[0m
[0m[ INFO] [1419629649.121321533]: [HrpsysSeqStateROSBridge] @Initilize name : HrpsysSeqStateROSBridge0 done[0m
[0m[ INFO] [1419629652.271751272]: [HrpsysSeqStateROSBridge] @onFinalize : HrpsysSeqStateROSBridge0[0m
[WARN] [WallTime: 1419629653.146166] [0.000000] Could not found CollisionDetector, waiting...
[WARN] [WallTime: 1419629654.150481] [0.000000] Could not found CollisionDetector, waiting...
[WARN] [WallTime: 1419629655.155263] [0.000000] Could not found CollisionDetector, waiting...
[WARN] [WallTime: 1419629656.159713] [0.000000] Could not found CollisionDetector, waiting...
[WARN] [WallTime: 1419629657.164887] [0.000000] Could not found CollisionDetector, waiting...
[WARN] [WallTime: 1419629658.269132] [0.000000] Could not found CollisionDetector, waiting...
[WARN] [WallTime: 1419629659.273211] [0.000000] Could not found CollisionDetector, waiting...
[WARN] [WallTime: 1419629660.277784] [0.000000] Could not found CollisionDetector, waiting...
[WARN] [WallTime: 1419629661.281914] [0.000000] Could not found CollisionDetector, waiting...
[ERROR] [WallTime: 1419629662.283350] [0.000000] Could not found CollisionDetector, exiting...
configuration ORB with  localhost : 2809
:
 * unrecognized tag rtconnect
 * unrecognized tag rtactivate
... logging to /home/travis/.ros/log/rostest-testing-worker-linux-5-2-1931-linux-4-42590583-29310.log
[ROSUNIT] Outputting test results to /home/travis/ros/ws_rtmros_hironx/build/test_results/hironx_ros_bridge/rostest-test_test-hironx-ros-bridge.xml
testtest_hironx_ros_bridge ... FAILURE!
FAILURE: test [test_hironx_ros_bridge] did not generate test results
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/runner.py", line 162, in fn
    self.assert_(os.path.isfile(test_file), "test [%s] did not generate test results"%test_name)
  File "/usr/lib/python2.7/unittest/case.py", line 420, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------

[ROSTEST]-----------------------------------------------------------------------

[testtest_hironx_ros_bridge][failed]

SUMMARY
[1;31m * RESULT: FAIL[0m
 * TESTS: 0
 * ERRORS: 0
[1;31m * FAILURES: 1[0m

ERROR: The following tests failed to run:
 * testtest_hironx_ros_bridge

rostest log file is in /home/travis/.ros/log/rostest-testing-worker-linux-5-2-1931-linux-4-42590583-29310.log
-- run_tests.py: execute commands
  /opt/ros/hydro/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge --package=hironx_ros_bridge --results-filename test_test-hironx-ros-bridge.xml /home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/test/test-hironx-ros-bridge.test 
-- run_tests.py: verify result "/home/travis/ros/ws_rtmros_hironx/build/test_results/hironx_ros_bridge/rostest-test_test-hironx-ros-bridge.xml"
<end of output>
Test time =  16.66 sec
----------------------------------------------------------
Test Failed.
"_ctest_hironx_ros_bridge_rostest_test_test-hironx-ros-bridge.test" end time: Dec 26 21:34 UTC
"_ctest_hironx_ros_bridge_rostest_test_test-hironx-ros-bridge.test" time elapsed: 00:00:16
----------------------------------------------------------
```

**Comment by k-okada** [comment]
i restart them and now it is fixed, all we need is just a little patience....

#302 is not related, because this happens only if we try to communicate with old version of hrpsys.
Off cause to add the test to check if compatible with old hrpsys in this repository may good things to do.

see https://github.com/fkanehiro/hrpsys-base/issues/435 to track this problem.

**Comment by 130s** [comment]
Looks to me still failing 
travis_fail_hironx287

**Comment by k-okada** [comment]
it seems we have gcc traoubles

```
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
make[3]: *** [rtc/AutoBalancer/CMakeFiles/AutoBalancer.dir/AutoBalancer.o] Error 4
make[3]: *** Waiting for unfinished jobs....
```

**Comment by k-okada** [comment]
passed, finally....

**Comment by 130s** [comment]
:beer:

**Pull request merged**
