### PR TITLE
Fix #65

### LINKED ISSUE #65: hironx_moveit_config does not depend on collada_tools
package.xml miss dependency to collada_tools and catkin_make says:

```
[rospack] Error: stack/package collada_tools not found
make[2]: *** [/home/jskuser/ros/groovy_catkin/src/rtm-ros-robotics/rtmros_hironx/hironx_moveit_config/models/HiroNX.urdf] Error 2
make[1]: *** [rtm-ros-robotics/rtmros_hironx/hironx_moveit_config/CMakeFiles/hironx_moveit_config_HiroNX_urdf.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

### PR DESCRIPTION
**Pull request by 130s**

### CODE REVIEW

**Comment by 130s** [comment]
Although failed with the same reason [with this comment](https://github.com/start-jsk/rtmros_hironx/pull/63#issuecomment-40556098), travis result looks good. But I'm not sure yet if this lets `collada_to_urdf` work as expected.

**Comment by 130s** [comment]
Re-triggered travis. This time I expect all-green with all depended .debs are available.

**Comment by 130s** [comment]
Only `ROS_DISTRO=groovy ROSWS=rosws BUILDER=rosbuild USE_DEB=true` is failing for the last few `travis` trials.

**Comment by k-okada** [comment]
1) it seems pr2_controller_msgs is missng
and
2) no `__init__.py`  in python2.7/dist-packages/hrpsys_ros_bridge, which is also commented on https://github.com/start-jsk/rtmros_hironx/issues/81#issuecomment-41637419

```
[HrpsysJointTrajectoryBridge] addJointGroup(larm), CORBA::SystemException INV_OBJREF
[rtmlaunch] Activate <- Inactive /localhost:2809/DataLoggerServiceROSBridge.rtc
Warning: Model HiroNX has empty joint ID in the valid IDs.
loading file:///opt/ros/groovy/share/openhrp3/share/OpenHRP-3.1/sample/model/longfloor.wrl
Humanoid node
Joint nodeWAIST
  Segment node BODY
The model was successfully loaded ! 
[rtmlaunch] Activate <- Inactive /localhost:2809/SequencePlayerServiceROSBridge.rtc
[rtmlaunch] Activate <- Inactive /localhost:2809/ForwardKinematicsServiceROSBridge.rtc
[rtmlaunch] Activate <- Inactive /localhost:2809/StateHolderServiceROSBridge.rtc
Traceback (most recent call last):
  File "/home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/test/test_hironx_ros_bridge.py", line 20, in <module>
    roslib.load_manifest('pr2_controllers_msgs')
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslib/launcher.py", line 62, in load_manifest
    sys.path = _generate_python_path(package_name, _rospack) + sys.path
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslib/launcher.py", line 93, in _generate_python_path
    m = rospack.get_manifest(pkg)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 159, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 198, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 190, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: pr2_controllers_msgs
ROS path [0]=/opt/ros/groovy/share/ros
ROS path [1]=/home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx
ROS path [2]=/opt/ros/groovy/share
ROS path [3]=/opt/ros/groovy/stacks
omniORB: ERROR -- the application attempted to invoke an operation
```

```
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Traceback (most recent call last):
  File "/opt/ros/groovy/share/hrpsys_ros_bridge/scripts/diagnostics.py", line 13, in <module>
    from hrpsys_ros_bridge.msg import MotorStates
ImportError: No module named hrpsys_ros_bridge.msg
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
```

**Comment by k-okada** [comment]
I think one straight forward solution is to release new version of rtmros_common [1] that solves above problem, but .travis.sh in [2] force install pr2-controllres and `__init__.py` so the problem is solved (although that is not a good way to pass the test)

[1] https://github.com/start-jsk/rtmros_common/issues/450
[2] https://github.com/start-jsk/rtmros_hironx/pull/86/files#diff-354f30a63fb0907d4ad57269548329e3R80

**Comment by k-okada** [comment]
another concern is that the test is passed on groovy/catkin, it said as follows and since it said `*TESTS: 0`, this means no test is running, may be due to https://github.com/start-jsk/rtmros_hironx/issues/81#issue-31861243 problem.

```
The model was successfully loaded ! 
Warning: Model HiroNX has empty joint ID in the valid IDs.
loading file:///opt/ros/groovy/share/openhrp3/share/OpenHRP-3.1/idl/../../..//share/OpenHRP-3.1/sample/model/longfloor.wrl
Humanoid node
Joint nodeWAIST
  Segment node BODY
The model was successfully loaded ! 
terminate called after throwing an instance of 'CORBA::OBJECT_NOT_EXIST'
testtest_hironx ... ok
testtest_hironx_ik ... ok

[ROSTEST]-----------------------------------------------------------------------


SUMMARY
[32m * RESULT: SUCCESS[0m
 * TESTS: 0
 * ERRORS: 0
 * FAILURES: 0
```

**Comment by 130s** [comment]
> another concern is that the test is passed on groovy/catkin, it said as follows and since it said *TESTS: 0, this means no test is running, may be due to #81 (comment) problem.

I agree although I still have no idea why `travis` only fails with a single combination. I think this is good to merge since the cause of failure is external to the suggested change.

**Pull request merged**
