### PR TITLE
Add missing install rule for calibration pkg

### PR DESCRIPTION
**Pull request by 130s**
- Adding missing launch
- <s>Add Kinect to the default URDF so that users won't have to add it on their own (http://wiki.ros.org/rtmros_nextage/Tutorials/CalibrateKinect#Before_Calibration). 
  - Confirmed that this model works even whithout calibration</s>

### CODE REVIEW

**Comment by 130s** [comment]
Please review @k-okada 
Does this break anything?

**Comment by k-okada** [comment]
if you assume users https://github.com/ros-drivers/openni_launch/blob/hydro-devel/launch/openni.launch
it will publishes tf and that will conflict , 
http://wiki.ros.org/rtmros_nextage/Tutorials/CalibrateKinect#Before_Calibration
is intend to "templary" fix urdf and revert after that, and start kinect with openni.launch that publishes tf, but if you include camera frame to urdf, be sure to run openni.launch without tf publishing, this behavior  can reproduce with hrpsys-simulation and real kinect camera hardware, so you can try.

travis also reported error.

**Comment by 130s** [comment]
I see.
So I think I split this PR; I removed the commit for kinect link and will open a new PR for it.
Now this PR only contains a fix to the missing install rule.

**Comment by k-okada** [comment]
If you want to calibrate Kinect, we have 3 strategy and super strongly start from 1st method, starting from step 3 too difficult for anyone;
1 manually change head-camera static tf and check if that is correct from Rviz
2 attach calibration board in the robot body and measure board-camera tf from CV tool and find head-camera tf
3 use http://wiki.ros.org/rtmros_nextage/Tutorials/CalibrateKinect#Before_Calibration

Please please please, start from 1st method;
Even so you have to find;
- how to mannualy change static tf of head-camera
- how to determine if that is correct on Rviz

**Comment by 130s** [comment]
Now travis passed for hydro. 
Adding Kinect to URDF is ticketed separately https://github.com/start-jsk/rtmros_hironx/issues/405.

**Pull request merged**
