### PR TITLE
fix to pass export TEST_TYPE=work_with_315_1_10

### PR DESCRIPTION
**Pull request by k-okada**
- hrpsys_client.py : show Hrpsys controller version info
- need to install hrpsys_315_1_9.hrpsys

### CODE REVIEW

**Comment by k-okada** [comment]
this still fails

**Comment by 130s** [comment]
Travis passed but I see #387 contains some commits from this. Do we still merge this, or close?

**Comment by k-okada** [comment]
do not maerge this, still working on that.
Please see travis log, i think it is failing.

## 

◉ Kei Okada

On Thu, Aug 13, 2015 at 11:09 AM, Isaac I.Y. Saito <notifications@github.com

**Comment by k-okada** [comment]
closing due to #387

**Pull request closed without merging**
