### PR TITLE
fix code with python

### PR DESCRIPTION
**Pull request by k-okada**
DO NOT MERGE, this is test code

### CODE REVIEW

**Comment by 130s** [comment]
Btw this PReq may need to be `rebase`d before merge (I downloaded and found the parent commits are very old).

**Comment by k-okada** [comment]
could you teach me how to `rebase` this, 'git rebase' ??

**Comment by 130s** [comment]
What I did was:

```
$ git fetch origin
$ git rebase origin/groovy-devel
```

But github on this PReq page doesn't show any backported result, so this `rebase` may not be necessary (I'm not yet sure how `git` works in this regard).

**Comment by k-okada** [comment]
On Wed, Jun 25, 2014 at 12:00 PM, Isaac Isao Saito notifications@github.com wrote:
git rebase origin/groovy-devel

thanks I rebased and it said 

```
$ git push k-okada rewrite_system_check_with_py 
Username for 'http://github.com': k-okada
Password for 'http://k-okada@github.com': 
To http://github.com/k-okada/rtmros_hironx
 ! [rejected]        rewrite_system_check_with_py -> rewrite_system_check_with_py (non-fast-forward)
error: failed to push some refs to 'http://github.com/k-okada/rtmros_hironx'
To prevent you from losing history, non-fast-forward updates were rejected
Merge the remote changes (e.g. 'git pull') before pushing again.  See the
'Note about fast-forwards' section of 'git push --help' for details.
```

so create new branch https://github.com/k-okada/rtmros_hironx/commits/rewrite_system_check_with_py2

do you think I can 

```
git push -f k-okada rewrite_system_check_with_py 
```

**Comment by 130s** [comment]
> do you think I can
> 
> git push -f k-okada rewrite_system_check_with_py 

I think you could have done that, though I'm not sure what's happening. If you just did `git rebase`, then the existing commit chain changes, like the one you're required when you squashed by `git rebase -i`.

**Comment by 130s** [comment]
Closing in favor of #119

**Pull request closed without merging**
