### PR TITLE
(acceptancetest_hironx.py) ver 1.0.

### PR DESCRIPTION
**Pull request by 130s**
Addressing https://github.com/tork-a/hironx_tutorial/issues/6, only for `hrpsys`.

Some tasks are yet missing but this commit should be minimally complete for `hrpsys` methods (ROS methods need to be written).

The change in `hironx_ros_bridge/test/test_hironx_ik.py` is not intended. I might have to revoke the change for that file.

### CODE REVIEW

**Comment by 130s** [comment]
> The change in hironx_ros_bridge/test/test_hironx_ik.py is not intended. I might have to revoke the change for that file.

I added comments for this change. Although unexpectedly included in this PReq, those changes seem reasonable to me. I'm a bit lazy to remove them from this Preq either but if necessary I'll fix it.

**Comment by k-okada** [comment]
> https://github.com/start-jsk/rtmros_hironx/commit/e7ea2712e7b89f22da7001691f8f431cfc7f74a8

sorry, privatize the function  `_test_set_target_pose` may my mistake

**Comment by emijah** [comment]
This code checks the return value of setTargetPose, but doesn't check whether the tool tip has actually moved to the desired position using the FK module. Is this intentional?
I think perhaps checking to see whether the joint angles are within bounds of the angles for the correct posture would be a better solution.
(I should send you a pull request with code, but I'm a bit tied up right now...)

**Comment by 130s** [comment]
@emijah could you please refer to the specific line? You can add your comments on the file view line-by-line.

**Comment by emijah** [comment]
Okay, will do that

**Comment by 130s** [comment]
Merging.
Thank you for the comment @emijah. That will be handled separately from this PReq.

**Pull request merged**
