### PR TITLE
(test-hironx.test) Add omninames script (partial fix to #117)

### PR DESCRIPTION
**Pull request by 130s**

### CODE REVIEW

**Comment by k-okada** [comment]
it seems there are component that assuming corba port 15005.

```
[rtmlaunch] SIMULATOR_NAME HiroNX(Robot)0
[rtmlaunch] check connection/activation
[31m[rtmlaunch] [ERROR] Could not Connect ( /localhost:15005/HiroNX(Robot)0.rtc:q , /localhost:15005/CollisionDetector0.rtc:qCurrent ):  Invalid CORBA naming service: localhost:15005 [0m
[31m[rtmlaunch] Could not Activate ( localhost:15005/CollisionDetector0.rtc ) :  Invalid CORBA naming service: localhost:15005 [0m
[hrpsys.py]  wait for RTCmanager :  None
[sensor_ros_bridge_connect.py]  wait for RTCmanager :  testing-worker-linux-7-2-14978-linux-9-28267248
configuration ORB with  localhost : 15005
[ERROR] Connection Failed with the Nameserver (hostname=localhost port=15005).
Make sure the hostname is correct and the Nameserver is running.
CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)
```

**Comment by k-okada** [comment]
this seems just a simple typo `args=value="$(arg corbaport)"`

**Comment by 130s** [comment]
My very bad. Fix just committed.

**Comment by 130s** [comment]
Only Groovy DEB is failing due to `ros-groovy-hrpsys-ros-bridge` not being built yet.

**Comment by 130s** [comment]
Looks like rooted in https://github.com/ros/dynamic_reconfigure/issues/29 that [prevented `ros-groovy-hrpsys-ros-bridge` from building](http://jenkins.ros.org/view/GbinP64/job/ros-groovy-hrpsys-ros-bridge_binarydeb_precise_amd64/115/console).

**Comment by 130s** [comment]
I'm tempted to merge this (and maybe others) that fail only on Groovy because the cause of the error seems to be clear (missing `dynamic_reconfigure` DEB). Objections?

**Comment by k-okada** [comment]
yes, you can merge it.

On Sat, Jun 28, 2014 at 11:00 AM, Isaac Isao Saito <notifications@github.com

**Comment by 130s** [comment]
:smiley_cat:

**Pull request merged**
