### PR TITLE
3D model offset fix

### PR DESCRIPTION
**Pull request by emijah**
Updated offset in collada file to accurately match the CAD model.
WIP because kawada-hironx.l hasn't been updated yet. Please tell me how to proceed.

### CODE REVIEW

**Comment by 130s** [comment]
Thank you. I'm waiting to Travis to be fixed in https://github.com/start-jsk/rtmros_hironx/pull/462 before we can start reviewing.

**Comment by emijah** [comment]
Just linking this PR to the issue that it should fix.
tork-a/rtmros_nextage#244

**Comment by 130s** [comment]
Is this still `WIP`?

**Comment by emijah** [comment]
@130s As far as the offset itself goes, it's final. I haven't confirmed with other generated files so I'm not sure what else will be affected.

**Comment by k-okada** [comment]
I think original problem
https://github.com/tork-a/rtmros_nextage/issues/244 has been
solved by
https://github.com/tork-a/rtmros_nextage/pull/245 for nextage users, and
that have huge side-effect since all users must remove 7mm offset if they
noticed that and explicitly wrote them in ther source code and if they did
not noticed this, newer version changes the arm position by 7mm.

I think the parched version (0.7.7) is already released so we need to
inform all nextage use for this huge change. That's first thing we have to
do.

After we confirm this work well in all uses, then we can merge this,
release just before next sync and send update information

2016年6月3日金曜日、Hajime SAITO<notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:

> @130s https://github.com/130s As far as the offset itself goes, it's
> final. I haven't confirmed with other generated files so I'm not sure what
> else will be affected.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/start-jsk/rtmros_hironx/pull/461#issuecomment-223500998,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAeG3CTjZtPMC17BStZe8X-1WLBAxLQYks5qH8lHgaJpZM4IZ6PT
> .

## 

## 

◉ Kei Okada

**Comment by 130s** [comment]
> I think the patched version (0.7.7) is already released so we need to inform all nextage use for this huge change. That's first thing we have to do.

Noted -- I will make an announcement.

> After we confirm this work well in all uses, then we can merge this, release just before next sync and send update information

But after we merge this PR we'll have to make another announcement for Hironx users, don't we? Why not merge this first and inform all NXO and Hironx users at the same time?

**Comment by k-okada** [comment]
On Sat, Jun 4, 2016 at 2:59 AM, Isaac I.Y. Saito notifications@github.com
wrote:

> But after we merge this PR we'll have to make another announcement for
> Hironx users, don't we? Why not merge this first and inform all NXO and
> Hironx users at the same time?
> 
fix for nxo users has been released, I mean that repo is synced from shadow-fixed to the release one so everyone can use them at this moment And for hiro, even if we merged this one right now, it will take another few months for next sync, and it seems existing users already write any of workaround for this issue https://github.com/tork-a/rtmros_nextage/issues/244#issuecomment-217384251 this means if we releaes this, they have to roll abck their 'workaround' and sometimes they implicitly change the target position due to this issue. So I think now everyone willing to merge this issue, some one might think "please do not change, we're writing code based on current version, even it has bugs on kinematics, we already find solution to deal with it within our code", So I thought if we can not release (sync) hiro package right now, we will announce nextage change and see users response and confirm everything goes well and then release for hiro. And if hiro users want to fix this problem, they might be fix

(model file in qnx . Is it correct?)

**Comment by 130s** [comment]
I see. While I thought the reason of why we'll make multiple announcements _may_ be a little too conservative, I guess we should do that considering the wide range of the userbase from classrooms to aircraft factory.

I just opened a ticket about NXO https://github.com/tork-a/rtmros_nextage/issues/246.
Will send an email to the mailinglist right away.

**Comment by 130s** [comment]
Announcement made for NEXTAGE Open users [1](https://github.com/tork-a/rtmros_nextage/issues/246), [2](https://groups.google.com/forum/#!topic/rtm-ros-robotics/rhZgTsbxbRg) two weeks ago and so far nothing has been heard.

Can we move foward merge this and make a new release?

**Comment by 130s** [comment]
> Announcement made for NEXTAGE Open users 1, 2 two weeks ago and so far nothing has been heard.
> 
> Can we move foward merge this and make a new release?

It's been half an year so I'm going ahead merge this one, and make a new release.

**Pull request merged**
