### PR TITLE
Add a testcase for checking #335

### PR DESCRIPTION
**Pull request by 130s**
Currently checks only roll and pitch. 
Yaw value to be checked will be added once yaw movement is realized.

### CODE REVIEW

**Comment by 130s** [comment]
Updated to add `yaw` movement check.

**Comment by 130s** [comment]
Travis keeps failing at [this line](https://github.com/start-jsk/rtmros_hironx/pull/347/files#diff-51d172c68579ab83b5e55475131a72fcR277):

```
    numpy.testing.assert_array_almost_equal(numpy.array(roll_r_post), numpy.array(roll_r_post_now), decimal=2)
```

I'm trying the same lines of code on simulation (i.e. non-test environment) and it works fine, so I don't know why this fails in the test.

```
:
[hironx_ros_bridge.rosunit-test_hironx_target/testSetTargetPoseBothArm][passed]
[hironx_ros_bridge.rosunit-test_hironx_target/test_setTargetPoseRelative_rpy][FAILURE]
Arrays are not almost equal to 2 decimals

(mismatch 33.3333333333%)
 x: array([-1.639, -1.57 , -3.073])
 y: array([-1.66475026, -1.56902256, -3.07304454])
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/test/test_hironx_target.py", line 277, in test_setTargetPoseRelative_rpy
    numpy.testing.assert_array_almost_equal(numpy.array(roll_r_post), numpy.array(roll_r_post_now), decimal=2)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 800, in assert_array_almost_equal
    header=('Arrays are not almost equal to %d decimals' % decimal))
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 636, in assert_array_compare
    raise AssertionError(msg)
--------------------------------------------------------------------------------

SUMMARY
 * RESULT: FAIL
 * TESTS: 21
 * ERRORS: 0
 * FAILURES: 1
:
```

**Comment by 130s** [comment]
I was able to work around the particular error above by relaxing the time constraint as follows, which, however, may not be acceptable depending on the situation (esp. considering that this test case is a contribution from an industry user).

```
-    self.robot.setTargetPoseRelative(RTM_JOINTGRP_LEFT_ARM, l_eef, dr=math.pi / 2, tm=0.5, wait=False)
+    self.robot.setTargetPoseRelative(RTM_JOINTGRP_LEFT_ARM, l_eef, dr=math.pi / 2, tm=0.75, wait=False)
```

Anyway, moving forward, the following error does not make sense at all; The pose `y: array([ 0.05588772, -1.56852967, -0.05571039])` is never achievable using the suggested test case on the simulation.

https://s3.amazonaws.com/archive.travis-ci.org/jobs/76931271/log.txt

```
:
[hironx_ros_bridge.rosunit-test_hironx_target/testSetTargetPoseBothArm][passed]
[hironx_ros_bridge.rosunit-test_hironx_target/test_setTargetPoseRelative_rpy][FAILURE]
Arrays are not almost equal to 2 decimals

(mismatch 66.6666666667%)
 x: array([ 3.073  , -1.57002, -3.073  ])
 y: array([ 0.05588772, -1.56852967, -0.05571039])
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/home/travis/ros/ws_rtmros_hironx/src/rtmros_hironx/hironx_ros_bridge/test/test_hironx_target.py", line 299, in test_setTargetPoseRelative_rpy
    numpy.testing.assert_array_almost_equal(numpy.array(init_r), numpy.array(init_r_now), decimal=2)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 800, in assert_array_almost_equal
    header=('Arrays are not almost equal to %d decimals' % decimal))
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 636, in assert_array_compare
    raise AssertionError(msg)
--------------------------------------------------------------------------------


SUMMARY
[1;31m * RESULT: FAIL[0m
 * TESTS: 21
 * ERRORS: 0
[1;31m * FAILURES: 1[0m
```

**Comment by k-okada** [comment]
using rpy to compare rotation matrix is not a good idea, use matrix or quaternion .

I think it better to divide this pr into several pieces, such as coding style (that should pass the test), add newer test case (that should pass existing test).

**Comment by 130s** [comment]
I somehow messed the commits so re-opened this #407 against indigo-devel.

**Pull request closed without merging**
