### PR TITLE
(hironx_client.py) Fix https://github.com/start-jsk/rtmros_hironx/issues/45

### PR DESCRIPTION
**Pull request by 130s**

### CODE REVIEW

**Comment by k-okada** [comment]
restart travis to see if what's happens, last time, hrspys-simulator crashes

**Comment by 130s** [comment]
> last time, hrspys-simulator crashes

That's what I started seeing since today on simulator (hrpsys-simulator
kepps failing and its GUI never shows up). Maybe hrpsys 315.1.8 .deb
brought something with it.

**Comment by 130s** [comment]
Well hrpsys-simulator runs without any problems from source with [this commit](https://github.com/start-jsk/hrpsys/commit/7dc1745189617501cc555d9083ed90e0ee6b575d).

**Comment by 130s** [comment]
And travis passed.

**Comment by k-okada** [comment]
3.1.5-8 did not includes .so files under opt/ros/hydro/lib so that may the reason of crashing.

**Comment by 130s** [comment]
Functionality is confirmed in https://github.com/start-jsk/rtmros_hironx/issues/52 on simulator.

**Comment by 130s** [comment]
The commit updated. Guessing `travis` will be retriggered soon?

**Pull request merged**
