### PR TITLE
(robot md5sum) Updated checksum to July 2014 version of files on QNX.

### PR DESCRIPTION
**Pull request by 130s**
@k-okada Below is how I updated md5sum. Does this look ok? Or is there better/easier way to do so?
1. Unzip tarball received from the manufacturer to `/home/rosuser/hironx_qnx_krc_nxo_20140717`. THe directory contains `/opt, /usr, /var`.
2. Run the following command yields a large `.py` file.
   
   ```
   $ rosrun hironx_ros_bridge create-md5sum.py /home/rosuser/hironx_qnx_krc_nxo_20140717
   ```
3. Manually copy-paste sections into corresponding `md5sum_*.py` per folder.

### CODE REVIEW

**Comment by k-okada** [comment]
I think you're deleting necessary files -> https://github.com/start-jsk/rtmros_hironx/pull/175/files#diff-e567231f6a14f66cec9fe2d75cdb5ab7L340

what I did is 

```
$ rosrun hironx_ros_bridge create-md5sum.py /home/rosuser/hironx_qnx_krc_nxo_20140717/usr/pkg/etc
$ rosrun hironx_ros_bridge create-md5sum.py /home/rosuser/hironx_qnx_krc_nxo_20140717/usr/local
...
```

and fix file path in generated md5sum_*.py, if I remember correctly

**Comment by 130s** [comment]
`/usr/local/lib/libCOSDynamic4.so.1` isn't found in the [latest tarball](https://github.com/start-jsk/hironx-package/commit/1c628035db52a2243407cca01bbfd05088661a43), only `libCOSDynamic4.so.1.3` looks similar.

**Comment by k-okada** [comment]
libCOSDynamic4.so.1 is symlink in my environment

```
$ tar -tvjf pkglocal_140718.tbz  | grep COSD
-rw-r--r-- root/root    369838 2011-08-10 14:04 usr/local/lib/libCOSDynamic4.a
-rw-r--r-- root/root    366571 2011-08-10 14:04 usr/local/lib/libCOSDynamic4.so.1.3
lrwxrwxrwx root/root         0 2014-07-03 22:42 usr/local/lib/libCOSDynamic4.so.1 -> libCOSDynamic4.so.1.3
lrwxrwxrwx root/root         0 2014-07-03 22:42 usr/local/lib/libCOSDynamic4.so -> libCOSDynamic4.so.1
-rw-r--r-- root/root       264 2011-08-10 13:58 usr/local/lib/pkgconfig/omniCOSDynamic4.pc
$ ls -al pkglocal_140718.tbz 
-rw-rw-r-- 1 k-okada k-okada 93932989  7月 23 19:49 pkglocal_140718.tbz
```

**Comment by k-okada** [comment]
did you check with `tar -tvjf pkglocal_140718.tbz  | grep COSD` in your environment?

**Comment by 130s** [comment]
> did you check with tar -tvjf pkglocal_140718.tbz | grep COSD in your environment?

It did find `/usr/local/lib/libCOSDynamic4.so.1`. Something must have been messed up. Re-doing now

**Comment by 130s** [comment]
Closing in favor of https://github.com/start-jsk/rtmros_hironx/pull/190

Again, something must have been wrong when I untar-ed.

**Pull request closed without merging**
