### PR TITLE
(hironx_kinect.launch) Generalize tf coord arg.

### PR DESCRIPTION
**Pull request by 130s**
Follow-up to https://github.com/start-jsk/rtmros_hironx/pull/252

### CODE REVIEW

**Comment by 130s** [comment]
Currently in the .launch file only the values of `Hiro014` is available. So for the other types of Hiro:
- the tf values need to be contributed by some robot owners (I don't), if we want to include those in the `.lanuch` file. 
- Until then, tf values can be passed like:
  
  ```
  $ roslaunch hironx_ros_bridge hironx_kinect.launch TF_COORD:="0.062367406594775215 0.07536259323525744 0.12330820494245931 -0.03346088258363324 0.1383150116022393 -0.014468436806528857"
  ```

**Comment by 130s** [comment]
@k-okada for the review

**Comment by k-okada** [comment]
Good, but XYZ:="..." RPY:="..." Is more informative???

2014年10月1日水曜日、Isaac I.Y. Saitonotifications@github.comさんは書きました:

**Comment by 130s** [comment]
I see. Commit updated. https://github.com/130s/rtmros_hironx/commit/6e3b52aa92bb163751e4f07b3c281c84019fa993

**Comment by k-okada** [comment]
nice

**Pull request merged**
