### PR TITLE
Launch collision detection by default.

### PR DESCRIPTION
**Pull request by 130s**
**Please do not merge yet** until I ask to do so.

Left todo:
- [x] https://github.com/start-jsk/rtmros_common/pull/455 also needs to be merged in order for this change to be valid.
- [x] Add `.rviz` file that enables `MarkerArray` by default to collision marker.
- [x] Withdraw the commit that puts [.conf file that looks like should be auto-generated](https://github.com/130s/rtmros_hironx/blob/9ee7b63b7a95e82df12a60803ffd3c3640e518b1/hironx_ros_bridge/conf/kawada-hironx.conf).
- [x] Add necessary configuration to the auto-generate `.conf` files (that are generated into [hironx_ros_bridge/conf](https://github.com/start-jsk/rtmros_hironx/tree/groovy-devel/hironx_ros_bridge/conf))

### CODE REVIEW

**Comment by 130s** [comment]
Addressing https://github.com/start-jsk/rtmros_hironx/issues/36

**Comment by 130s** [comment]
Image with real robot: collision_natto_hiro014

**Comment by 130s** [comment]
To modify `.rviz` file to enable `Marker Array` by default, I'm facing [this perplexity I asked about on answers.ros.org](http://answers.ros.org/question/159666/best-practice-for-customizing-rviz-file-moveit-setup-assistant-creates/).

**Comment by 130s** [comment]
1af77b2 adds `natto-view`. 

> To modify .rviz file to enable Marker Array by default, I'm facing [this perplexity I asked about on answers.ros.org](http://answers.ros.org/question/159666/best-practice-for-customizing-rviz-file-moveit-setup-assistant-creates/).

I chose to rather apply tentative solution here to move forward at this moment.

Waiting https://github.com/start-jsk/rtmros_common/pull/455 to be merged.

**Comment by 130s** [comment]
I think I've added all necessary changes. So ready to be reviewed and get merged if ready.

> Add necessary configuration to the auto-generate .conf files (that are generated into hironx_ros_bridge/conf)

I didn't touch that part because I don't fully understand the purpose of separating `nosim` files (asked in https://github.com/start-jsk/rtmros_hironx/issues/92), and also, more importantly, file path on QNX for the real robot is fixed anyway so that auto-generation might not make much sense here.

I feel not like squashing, since this is a package downstream enough and there might be rooms for each commit to be reviewed even in the future.

**Comment by 130s** [comment]
Movie taken from simulation

<iframe width="420" height="315" src="//www.youtube.com/embed/89nafN1fHPk" frameborder="0" allowfullscreen></iframe>

http://youtu.be/89nafN1fHPk

**Comment by 130s** [comment]
All `travis` variants failed #what_a_terrible_commit. 
Restarted.

**Comment by k-okada** [comment]
this won't pass the travis test,  since travis uses hironx_ros_bridge.launch with simulation, but your change assuming it is real robot. https://github.com/start-jsk/rtmros_hironx/pull/89/files#diff-c61d113b474992382cc835f0eff0f44eR7

```
test/hironx-rosbridge-test.test
  -> launch/hironx_ros_bridge_simulation.launch
    -> launch/hironx_startup.launchl
   -> launch/hironx_ros_bridge.launch
```

I think we should create launch/hirnox_ros_bridge_real.launch that include launch/hironx_ros_bridge.launch ( hironx_startup.laucn is not needed)

**Comment by 130s** [comment]
I see, I must have messed up inputs into .launch files. I'll fix this today with a real robot and simulation.

**Comment by 130s** [comment]
> I think we should create launch/hirnox_ros_bridge_real.launch that include launch/hironx_ros_bridge.launch ( hironx_startup.laucn is not needed)

As long as we and users know which launch files are for what purpose, current setting (as follows) shouldn't be too bad.
- `hironx_rosbridge_simulation.launch` depends on:
  - hironx_startup.launch
  - hironx_rosbridge.launch
- `hironx_rosbridge.launch` depends on:
  - hironx_rosbridge.launch

How about me adding comments in `.launch` files to explain the purpose of each?

**Comment by k-okada** [comment]
all travis failed, due to https://github.com/start-jsk/rtmros_common/pull/461 ?? any way restart travis and see what will happens

**Comment by k-okada** [comment]
travis failed, something wrong with PR

**Comment by 130s** [comment]
Finally travis passes. I'll squash and merge

**Comment by k-okada** [comment]
rtmlaunch(https://github.com/start-jsk/rtmros_common/blob/master/openrtm_tools/scripts/rtmlaunch.py), start corba nameserver with given `corbaport` in launchfile, but when you use roslaunch, then we have to use default corba port (2809) and `add_rostest()` command on CMakeLists.txt uses roslaunch so custom corbaport is not able to use in test code. 
Also https://github.com/start-jsk/rtmros_hironx/blob/groovy-devel/.travis.yml#L91 uses `rostest` command.

Ubuntu run corba nameserver by default, but ros jenkins server disable them, so if we want to run test on ros jenkins server, we have to launch nameserver by yourself
as https://github.com/start-jsk/hrpsys/blob/master/test/start_omninames.sh. This is dangerous because launch file is not ensure the order of execution of the node and that's why we created rtmlaunch script.
 https://github.com/ros-infrastructure/jenkins_scripts/issues/67

**Pull request merged**
