### PR TITLE
need more precision on end_effector's location

### PR DESCRIPTION
**Pull request by k-okada**
this code is introduced in #338 but turned out that impedance controller is not working well on simulaiton,
for example, we use orinal parameter on rarm and fixed version on larm, `localR` of rarm is not a good value and that makes impedance controle very unstable.

```
[ic] End Effector [rarm]RARM_JOINT5 CHEST_JOINT0
[ic]   target = RARM_JOINT5, base = CHEST_JOINT0
[ic]   localPos =     [0,  0,  0][m]
[ic]   localR =     [ 3.13478e-05,  1.99151e-05,      1.00002]
    [     1.00002, -3.29388e-06, -1.47259e-05]
    [ 1.99151e-05,      1.00002, -3.29388e-06]
[ic] End Effector [larm]LARM_JOINT5 CHEST_JOINT0
[ic]   target = LARM_JOINT5, base = CHEST_JOINT0
[ic]   localPos =     [0,  0,  0][m]
[ic]   localR =     [1.40361e-09, 7.01805e-10,           1]
    [          1, 1.40361e-09, 7.01805e-10]
    [7.01805e-10,           1, 1.40361e-09]
```

screenshot from 2016-12-22 15 25 29

### CODE REVIEW

**Comment by k-okada** [comment]
to test this, run ` rtmlaunch hironx_ros_bridge hironx_startup.launch` and 
```
In [1]: hcf.startImpedance('larm')
In [2]: hcf.startImpedance('rarm')
```
on `ipython -i ./hironx.py`

**Comment by 130s** [comment]
I got a video like [this](https://drive.google.com/file/d/0Bw_hbVS3wTLyS0RUZk0wRTI1eEU/view?usp=sharing) using this PR. Does this look like what you intended?

**Comment by k-okada** [comment]
This is what I got after this PR.


https://drive.google.com/file/d/0B5hXrFUpyR2iT2dfMkhJUXdUVEE/view?usp=sharing

```
$ cat hoge.py 
#!/usr/bin/env python

from hironx_ros_bridge import hironx_client

robot = hironx_client.HIRONX()
robot.init(robotname="HiroNX(Robot)0")

from time import sleep
print ";; INFO ;; start impedance"
robot.startImpedance('larm')
sleep(1)
print ";; INFO ;; set reference force"
robot.seq_svc.setWrenches([0,0,-10,0,0,0, 0,0,0.0,0,0,0], 0.1)
sleep(5)
print ";; INFO ;; more reference force"
robot.seq_svc.setWrenches([0,0,-50,0,0,0, 0,0,0.0,0,0,0], 0.1)
sleep(5)
print ";; INFO ;; stop impedance"
robot.seq_svc.setWrenches([0,0,0,0,0,0, 0,0,0.0,0,0,0], 1)
robot.stopImpedance('larm')
sleep(1)
```

**Comment by 130s** [comment]
I cloned cleanly this PR and now I have [this video](https://drive.google.com/open?id=0Bw_hbVS3wTLycU5ITzIzdGZpOHM). I see the impedance feature is working, but as you see at `robot.seq_svc.setWrenches([0,0,-10,0,0,0, 0,0,0.0,0,0,0], 0.1)`, both arms went down (it seems to me they are gone uncontrollable).

So I modified [the sample script](https://github.com/start-jsk/rtmros_hironx/pull/482#issuecomment-269074248) to use `goInitial` right after the arms went down, then after the arms returning to the init pose, they are in control with the impedance feature on. [Video](https://drive.google.com/open?id=0Bw_hbVS3wTLyc25BRl9kZ2IyUkE).

So what I do not understand: Is what I see after `setWrenches([0,0,-10,0,0,0, 0,0,0.0,0,0,0], 0.1)` as intended? Then why does that happen?

```
$ more hoge.py
#!/usr/bin/env python

from hironx_ros_bridge import hironx_client

robot = hironx_client.HIRONX()
robot.init(robotname="HiroNX(Robot)0")

from time import sleep
print ";; INFO ;; start impedance"
robot.startImpedance('larm')
sleep(1)
print ";; INFO ;; set reference force"
robot.seq_svc.setWrenches([0,0,-10,0,0,0, 0,0,0.0,0,0,0], 0.1)
sleep(5)
robot.goInitial()
print ";; INFO ;; more reference force"
robot.seq_svc.setWrenches([0,0,-50,0,0,0, 0,0,0.0,0,0,0], 0.1)
sleep(5)
print ";; INFO ;; stop impedance"
robot.seq_svc.setWrenches([0,0,0,0,0,0, 0,0,0.0,0,0,0], 1)
robot.stopImpedance('larm')
sleep(1)
```

**Comment by 130s** [comment]
I cloned cleanly this PR and now I have [this video](https://drive.google.com/open?id=0Bw_hbVS3wTLycU5ITzIzdGZpOHM). I see the impedance feature is working, but as you see at `robot.seq_svc.setWrenches([0,0,-10,0,0,0, 0,0,0.0,0,0,0], 0.1)`, both arms went down (it seems to me they are gone uncontrollable).

So I modified [the sample script](https://github.com/start-jsk/rtmros_hironx/pull/482#issuecomment-269074248) to use `goInitial` right after the arms went down, then after the arms returning to the init pose, they are in control with the impedance feature on. [Video](https://drive.google.com/open?id=0Bw_hbVS3wTLyc25BRl9kZ2IyUkE).

So what I do not understand: Is what I see after `setWrenches([0,0,-10,0,0,0, 0,0,0.0,0,0,0], 0.1)` as intended? Then why does that happen?

```
$ more hoge.py
#!/usr/bin/env python

from hironx_ros_bridge import hironx_client

robot = hironx_client.HIRONX()
robot.init(robotname="HiroNX(Robot)0")

from time import sleep
print ";; INFO ;; start impedance"
robot.startImpedance('larm')
sleep(1)
print ";; INFO ;; set reference force"
robot.seq_svc.setWrenches([0,0,-10,0,0,0, 0,0,0.0,0,0,0], 0.1)
sleep(5)
robot.goInitial()
print ";; INFO ;; more reference force"
robot.seq_svc.setWrenches([0,0,-50,0,0,0, 0,0,0.0,0,0,0], 0.1)
sleep(5)
print ";; INFO ;; stop impedance"
robot.seq_svc.setWrenches([0,0,0,0,0,0, 0,0,0.0,0,0,0], 1)
robot.stopImpedance('larm')
sleep(1)
```

**Comment by k-okada** [comment]
> both arms went down (it seems to me they are gone uncontrollable).

that is not a good, please issue robot.goInitial(), then run hoge.py

another tip is when you take video, use half width terminal with larger font for readbility,

**Comment by 130s** [comment]
With running `goInitial` before `setWrenches` (modified code below) I think it's working as intended. `setTargetPoseRelative` worked too.

For instructing users, is making "moving joints BEFORE starting impedance control" a requirement sufficient?

```
#!/usr/bin/env python

from hironx_ros_bridge import hironx_client

robot = hironx_client.HIRONX()
robot.init(robotname="HiroNX(Robot)0")

from time import sleep
print ";; INFO ;; start impedance"
robot.startImpedance('larm')
sleep(1)
robot.goInitial(tm=2)
print ";; INFO ;; set reference force"
robot.seq_svc.setWrenches([0,0,-10,0,0,0, 0,0,0.0,0,0,0], 0.1)
sleep(5)
robot.goInitial()
print ";; INFO ;; more reference force"
robot.seq_svc.setWrenches([0,0,-50,0,0,0, 0,0,0.0,0,0,0], 0.1)
sleep(5)
print ";; INFO ;; stop impedance"
robot.seq_svc.setWrenches([0,0,0,0,0,0, 0,0,0.0,0,0,0], 1)
robot.stopImpedance('larm')
sleep(1)
```

**Comment by 130s** [comment]
> For instructing users, is making "moving joints BEFORE starting impedance control" a requirement sufficient?

I think instructing so may not be even necessary because I assume robot users usually activate impedance control once the arms are calibrated by `checkEncoders`.

**Comment by k-okada** [comment]
`checkEncoders` and issue reported in this PR is different thing, the problem reported this was that rotation matrix is not orthogonal, see https://github.com/fkanehiro/hrpsys-base/commit/c7602e8c2c61cd7022bcbf35198e33bd7402d1cb#commitcomment-20270283 for more info.

**Pull request merged**
