### PR TITLE
(hrpsys client) Workaround openhrp3 import issue

### PR DESCRIPTION
**Pull request by 130s**
DO NOT MERGE YET.

This PR is trying to work around the issue https://github.com/fkanehiro/openhrp3/issues/42. As of 2/13/2015 the issue https://github.com/fkanehiro/openhrp3/issues/42 is the priority. Once it's resolved, we can test with this PR.

### CODE REVIEW

**Comment by 130s** [comment]
With 804f209 (that follows https://github.com/start-jsk/openhrp3/issues/57#issuecomment-74311210), this error still occurs.

```
/home/heisei/indigo_trusty/cws_hironxo/src/start-jsk/rtmros_hironx/hironx_ros_bridge/scripts/hironx.py in <module>()
     41     roslib.load_manifest('hironx_ros_bridge')
     42 
---> 43 from hironx_ros_bridge import hironx_client
     44 from hironx_ros_bridge.ros_client import ROS_Client
     45 

/home/heisei/indigo_trusty/cws_hironxo/src/start-jsk/rtmros_hironx/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py in <module>()
     55 
     56 
---> 57 SWITCH_ON = OpenHRP.RobotHardwareService.SWITCH_ON
     58 SWITCH_OFF = OpenHRP.RobotHardwareService.SWITCH_OFF
     59 _MSG_ASK_ISSUEREPORT = 'Your report to ' + \

NameError: name 'OpenHRP' is not defined
```

**Comment by 130s** [comment]
Now good for the review.

**Comment by k-okada** [comment]
this is no longer requried

**Comment by k-okada** [comment]
see https://github.com/start-jsk/openhrp3/issues/57#issuecomment-74376700

**Comment by 130s** [comment]
Got it; I confirmed without this PR hironx.py works (using 5ffafe218312c61f5c7937c0b770beebf92b3910).

**Pull request closed without merging**
