### PR TITLE
(hironx_client.py) Fix #102

### LINKED ISSUE #102: Let HIRONX.getCurrent{ Pose, Position, RPY } return eef of both arms with empty argument
Is it a bad idea? 

Every time I started using these methods, I forgot the exact spelling of joint names and thus have to search the name of joint by `robot.Groups`.  And I personally never looked up to other joints than joint-5.

So with what I propose users would be able to do something like:

```
In [6]: robot.getCurrentPosition()
Out[6]: 
 LARM_JOINT5: [0.3255751432930864, 0.1823632083754606, 1.0376247521028383]
 RARM_JOINT5: [0.3255751432930864, -0.1823632083754606, 1.0376247521028383]
```

### PR DESCRIPTION
**Pull request by 130s**
DO NO MERGE YET because:
- [ ] This needs https://github.com/fkanehiro/hrpsys-base/pull/234 to be merged, AND hrpsys `315.2.3` (or anything newer than the current `315.2.2`) released.
- [ ] I'll have to add an unit test case.

### CODE REVIEW

**Comment by 130s** [comment]
We also need hrpsys 315.2.3 (or anything newer than the current 315.2.2. I updated the original post).

**Comment by k-okada** [comment]
how about add `_EEF_JONT_NAMES = []` in the `hrpsys_config.py` and `def getCurrentRPY(self, lname=None, eef_names=_EEF_JOINT_NAMES)` in hrpsys_config.py so that we do not need to redefine many functions in downstream package.

**Comment by 130s** [comment]
> how about add _EEF_JONT_NAMES = [] in the hrpsys_config.py and def getCurrentRPY(self, lname=None, eef_names=_EEF_JOINT_NAMES) in hrpsys_config.py so that we do not need to redefine many functions in downstream package.

Thank you for the suggestion. It actually works out pretty well.
- [PReq in hrpsys](https://github.com/130s/hrpsys-base/commit/b0d63aabbbddf4a5ad3f39662a9e327f7c4da756) (and [the comment about it](https://github.com/fkanehiro/hrpsys-base/pull/234#issuecomment-47319266))
- [Commit in hironx_ros_bridge](https://github.com/130s/rtmros_hironx/commit/c80a302f2298bb2866b5e198fe338f60698a4fda) now becomes much simpler.

**Comment by 130s** [comment]
See https://github.com/start-jsk/rtmros_hironx/commit/ac2ec5aba9cad24216a39614014d769151077907 that removes all the updated methods in this PReq -- we better depend on upstream.

**Pull request closed without merging**
