### PR TITLE
(acceptancetest_hironx.py) Add tasks written in ROS. Add ROS client.

### PR DESCRIPTION
**Pull request by 130s**
Some tasks that involve `Cartesian` and didn't look straightforward in ROS, are not implemented yet (task 4, 7). 

At this time `ROS_Client` class is added for the first time. This class provides simplified low-level ROS API (using `pr2_controllers_msgs.msg.JointTrajectoryAction`) for Hiro-NXO robot. Features available at this moment are still minimum, but as seen in task 6 in acceptance test py, interruption is achieved.

As mentioned above what's still missing is Cartesian control, which is possible with the same ROS interface, `JointTrajectoryAction`. [Explained in this tutorial](http://wiki.ros.org/pr2_controllers/Tutorials/Moving%20the%20arm%20through%20a%20Cartesian%20pose%20trajectory), though, it requires to create a `ROS Service` type, so `HrpsysConfigurator.setTargetRelative` seems simpler.

That said, I'm wondering whether (a) I should manage to implement task 4 and 7 in ROS or (b) leave Cartesian features to `hrpsys`. 

If we choose (b), a unified client class that provides all available features while encapsulating the detail of both hrpsys and ROS might be very useful for the users.
Also, creating a unified class doesn't mean users wouldn't be able to write directly in `hrpsys` nor `ROS`; API of those are still open to users.

### CODE REVIEW

**Comment by k-okada** [comment]
very good!!!  here is my comment. these are just my preference, so you can merge if current patch is better.

1) AcTestRos class  in acceptancetest_hironx.py is called from AcceptanceTest_Hiro class , but there are no AcTestRTM class, A test code for RTM is directly written in AcceptanceTest_Hiro class. I prefer to create AcTestRTM class or create acceptancetest_hironx_ros.py file and rename current file as acceptancetest_hironx_rtm.py, may be latter case is fine because if you like rtm, then you check *_rtm.py file and if you controll everything from ros, then you'll check *_ros.py file. These files are also used for tutorial pages.

2) it seems we pass `jointgroups` ROS_clinet but it is not necessary at this moment, and since we can get this infrormation from existing actionlib states, or parameterserers (we may need to change source code) , I think we do not need to pass jointgroups to ROS_client.

**Comment by 130s** [comment]
For (1), yes that's valid feeling...in fact this PReq isn't perfectly re-usable and requires refactoring. In addition to what you mentioned, my plan is to add unit tests that call the methods in these acceptancetest\* classes. So in the end in my plan we'll have:

```
hironx_ros_bridge
|- src
   |- abst_acceptancetest.py
   |- acceptancetest_ros.py
   |- acceptancetest_rtm.py
|- test
   |- test_acceptancetest_ros.py  (depends on src/acceptancetest_ros.py)
   |- test_acceptancetest_rtm.py  (depends on src/acceptancetest_rtm.py)
```

Reason why test files call the files in src instead of writing everything in test, is because I found that acceptance test scripts have multiple users and situations: 
- At sales pitch. We might want to add "run task-by-task" feature (discussed somewhere I can't find)
- Who does the inspection before shipping.
- Manufacturer checks compatibility with the software.
- Robot user/purchaser:
  - see the available functionality when they receive it.
  - check upon troubleshooting.

So write the behavior in the files in `src`, and write in `test` things only specific to unit testing.

**Comment by k-okada** [comment]
looks good to me, just to makes sure, `- abst_acceptancetest.py` is just calls both 
`acceptancetest_ros.py` and `acceptancetest_rtm.py`?

**Comment by 130s** [comment]
Travis keeps failing.

Turned out the test is stuck at [this line](https://github.com/start-jsk/rtmros_hironx/pull/171/files#diff-f9592097d70ddcac8ad91644f3717047R123).

I suspect while in `ROS_Client.__init__`, not all controllers that it wants to instantiate are initiated yet?.

```
bobkur@yayoi:~$ unset ROS_MASTER_URI && export ROS_MASTER_URI=http://localhost:22422
bobkur@yayoi:~$ rosnode info /test_hironx 
--------------------------------------------------------------------------------
Node [/test_hironx]
Publications: 
 * /larm_controller/joint_trajectory_action/cancel [actionlib_msgs/GoalID]
 * /larm_controller/joint_trajectory_action/goal [pr2_controllers_msgs/JointTrajectoryActionGoal]
 * /rosout [rosgraph_msgs/Log]

Subscriptions: 
 * /clock [unknown type]
 * /larm_controller/joint_trajectory_action/feedback [unknown type]
 * /larm_controller/joint_trajectory_action/status [unknown type]
 * /larm_controller/joint_trajectory_action/result [unknown type]

Services: 
 * /test_hironx/get_loggers
 * /test_hironx/set_logger_level


contacting node http://yayoi:40002/ ...
Pid: 11029
Connections:
 * topic: /rosout
    * to: /rosout
    * direction: outbound
    * transport: TCPROS
```

**Comment by 130s** [comment]
Turned out `rostest` is somehow stuck at [SimpleActionClient.wait_for_server()](https://github.com/start-jsk/rtmros_hironx/pull/171/files#diff-857478fb2f83dd45b4a5fee7ca797b9cR79).

**Comment by 130s** [comment]
Travis goes green now. DON'T MERGE as I'm still adding changes.

**Comment by 130s** [comment]
Link to travis disappeared. Trying to trigger it by adding comment

**Comment by 130s** [comment]
Travis re-appears. 

Ready for the review.

**Comment by 130s** [comment]
Close and reopening; Link to travis disappeared again, test result isn't found.

**Comment by 130s** [comment]
@k-okada I'm confident that the classes are now hopefully as optimized as you requested.

**Comment by k-okada** [comment]
thanks!!!

**Pull request merged**
